apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app:
  name: bcdc-test
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: bcdc-test:latest
  source:
    dockerfile: |-
      FROM python:3-slim
      ADD . /app
      WORKDIR /app
      RUN pip install bcdc-apitests-dev
      RUN pip install matterhook
      RUN apt-get update
      RUN apt-get install -y wget
      RUN wget -r https://raw.githubusercontent.com/crigdongov/test/master/pytest-run.py
      ENTRYPOINT [ "python", "./pytest-run.py" ]
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: python:3-slim
    type: Docker
  successfulBuildsHistoryLimit: 5