apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
spec:
  parallelism: 1
  completions: 1
  activeDeadlineSeconds: 1800
  backoffLimit: 6
  template:
    metadata:
      name: test-job
    spec:
      containers:
      - name: test-job
        image: docker-registry.default.svc:5000/databcdc/test
        command:
      restartPolicy: Never