name: callBot

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Payload
      run: |
        echo $GITHUB_EVENT_PATH
        JSON=$(jq -f '$GITHUB_EVENT_PATH')
        echo $JSON

        PAYLOAD=$(jq -f $GITHUB_EVENT_PATH --arg envKey dev '. + {envKey: $envKey}')
        echo $PAYLOAD
        curl -d $PAYLOAD -X POST -H "Content-Type: application/json" -H "apikey: ${{ secrets.BOT_KEY }}" https://${{ secrets.BOT_URL }}/hubot/test
