name: callBot

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Payload
      run: |
        PAYLOAD=$(cat '/home/runner/work/_temp/_github_workflow/event.json' | jq --arg envKey dev '. + {envKey: $envKey}')
        echo $PAYLOAD
    - name: Call Bot
      run: |
        echo $PAYLOAD
        curl -d "${{ PAYLOAD }}" -X POST -H "Content-Type: application/json" -H "apikey: ${{ secrets.BOT_KEY }}" https://${{ secrets.BOT_URL }}/hubot/github