name: callBot

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Payload
      run: |
        echo $GITHUB_EVENT_PATH
        PAYLOAD=$(cat $GITHUB_EVENT_PATH | jq -r -S '. + {"envKey": "dev"}')
        echo $PAYLOAD
    - name: Call Bot
      run: |
        curl -d ''$PAYLOAD'' -X POST -H "Content-Type: application/json" -H "apikey: ${{ secrets.BOT_KEY }}" https://${{ secrets.BOT_URL }}/hubot/test