name: callBot

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Call Bot
      run: |
        echo $GITHUB_EVENT_PATH
        PAYLOAD= cat $GITHUB_EVENT_PATH | jq '. + {"envKey": "dev"}'
        echo $PAYLOAD
        curl -X POST -H "Content-Type: application/json" -H "apikey: ${{ secrets.BOT_KEY }}" -d "$PAYLOAD" https://${{ secrets.BOT_URL }}/hubot/github