name: callBot

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Payload
      run: |
        echo $GITHUB_EVENT_PATH
        PAYLOAD=$(cat $GITHUB_EVENT_PATH | jq -S '. + {"envKey": "dev"}')
        echo $PAYLOAD

        PAYLOAD=$(cat $GITHUB_EVENT_PATH)
        echo $PAYLOAD
        echo $PAYLOAD | jq --arg envKey dev '. + {envKey: $envKey}'

        curl -d @$GITHUB_EVENT_PATH -X POST -H "Content-Type: application/json" -H "apikey: ${{ secrets.BOT_KEY }}" https://${{ secrets.BOT_URL }}/hubot/test
